apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: hztvx0muh-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/hztvx0muh-java-quarkus-gitops